-- Aylek Sales — Close-01 agent + proposals.
--
-- Item 8 of the master brief. Adds the schema for the Close-01 agent's
-- HTML proposal flow + Stripe Payment Link checkout. Replaces the
-- old email-only proposal_review path going forward (back-compat:
-- existing proposal_review approvals keep working unchanged).
--
-- Five additions, all back-compat:
--   1. proposals table — one row per HTML proposal generated by
--      Close-01. Carries the HTML body, Stripe payment link metadata,
--      and a per-proposal token used by the public /p/[token] route.
--   2. Indexes on token (lookup) + (status, created_at) (Close-01 cron
--      sweeps).
--   3. RLS — client-scoped (Phase 4 pattern) + service-role bypass
--      (Item 1 pattern).
--   4. approvals.type += 'deal_cold' — Close-01 opens these when a
--      proposal goes cold (no view in 48h or no accept in 5 days after
--      view).
--   5. NOTE: NO pricing_cents column on playbooks — per the master
--      brief refinement, pricing is read from the JSON playbook
--      payload, not a dedicated column. Close-01 handles both the
--      "price is on file" + "price is null, follow up manually" paths.
--
-- Apply on top of 0016_playbook_segments.sql via the Supabase SQL editor.

-- ── 1. Proposals table ───────────────────────────────────────────────────
create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  client_id uuid references public.clients(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  meeting_id uuid references public.meetings(id) on delete set null,
  meeting_note_id uuid references public.meeting_notes(id) on delete set null,
  html_content text not null,
  subject text not null,
  status text not null default 'sent' check (status in (
    'draft','sent','viewed','accepted','paid','expired','rejected'
  )),
  stripe_payment_link_id text,
  stripe_payment_link_url text,
  amount_cents int,
  currency text default 'usd',
  view_count int not null default 0,
  viewed_at timestamptz,
  accepted_at timestamptz,
  paid_at timestamptz,
  expires_at timestamptz,
  followup_sent_at timestamptz,
  cold_flagged_at timestamptz,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists proposals_token_idx on public.proposals(token);
create index if not exists proposals_status_idx on public.proposals(status, created_at desc);
create index if not exists proposals_client_idx on public.proposals(client_id, created_at desc);
create index if not exists proposals_lead_idx on public.proposals(lead_id, created_at desc);

-- ── 2. RLS — client-scoped + service-role bypass ─────────────────────────
alter table public.proposals enable row level security;

drop policy if exists "client_scoped_proposals" on public.proposals;
create policy "client_scoped_proposals" on public.proposals
  for all
  using (
    public.is_admin()
    or (client_id is not null and public.has_client_scope(client_id))
  )
  with check (
    public.is_admin()
    or (client_id is not null and public.has_client_scope(client_id))
  );

drop policy if exists "service_role_bypass" on public.proposals;
create policy "service_role_bypass" on public.proposals
  for all
  using (
    auth.role() = 'service_role'
    or pg_has_role(current_user, 'postgres', 'member')
  )
  with check (
    auth.role() = 'service_role'
    or pg_has_role(current_user, 'postgres', 'member')
  );

-- ── 3. Extend approvals.type for deal_cold ───────────────────────────────
alter table public.approvals drop constraint if exists approvals_type_check;
alter table public.approvals add constraint approvals_type_check
  check (type in (
    'lead_list',
    'strategy_change',
    'human_stage_task',
    'proposal_review',
    'playbook_approval',
    'reply_review',
    'segment_proposal',
    'deal_cold'
  ));
